docs:
  changed-files:
    - any-glob-to-any-file: "docs/**"

front:
  changed-files:
    - any-glob-to-any-file: "front/**"

back:
  changed-files:
    - any-glob-to-any-file: "back/**"

hotfix:
  base-branch: "main"

